### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fMichaleczek** [Stroniax/PSSharp.Tools#1]
Your repository is very amazing and I found it interesting to learn SMA and C#. 

I don't find any license file in the repository, so I want to ask if could you clarify this point ? 

Context : 
https://twitter.com/_Flavien/status/1549206992601899008?s=20&t=3G1jWoFr_i3-pMi_FIdG5A

Thanks 🙂

**Comment by Stroniax** [comment]
I've added an MIT license to this project. Thank you for bringing this up.
